FROM mediagoblin/mediagoblin:@PACKAGE_VERSION@ AS mediagoblin

FROM nginx:latest

ENV MAX_BODY_SIZE=100m
ENV SERVER_NAME=mediagoblin
ENV PASTE_SERVICE=paste
ENV PASTE_PORT=6543

COPY nginx.conf.template /etc/nginx/templates/default.conf.template
# Copy the static files so nginx can serve them directly
COPY --from=mediagoblin /opt/mediagoblin/mediagoblin/static/ /opt/mediagoblin/mediagoblin/static/
# Note: for nginx to be able to serve the instance's media, it needs to be
# available at /srv/mediagoblin/user_dev/{media,theme_static,plugin_static}.
# The easiest is to mount the whole MediarGoblin data directory to /srv.
